### ISSUE TITLE
Error when deactivating package 

### ISSUE THREAD

**Issue by lexicalunit** [bh/atom-python-isort#33]
Occurs for me every time the package gets deactivated. Only tested in Atom 1.16.0 beta so far.

```
package.coffee:447 Error deactivating package 'atom-isort' TypeError: _ref1.dispose is not a function
    at Object.deactivate (/Users/me/.atom/packages/atom-isort/lib/index.coffee:53:14)
    at Package.module.exports.Package.deactivate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:722:20)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:643:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:347:21
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.pushAtKeyPath (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:361:12)
    at Package.module.exports.Package.disable (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:85:26)
    at PackageManager.module.exports.PackageManager.disablePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:183:16)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:336:23)
 ```

**Comment by lexicalunit** [comment]
I believe [`detach()`](https://api.jquery.com/detach/) should be called instead of `dispose()`. From a cursory review I don't see `dispose()` defined for a `View` object. It's also worth noting here that `space-pen` and `atom-space-pen-view` are deprecated and [will soon be removed from Atom entirely](http://blog.atom.io/2017/03/09/atom-1-15.html). It would probably be worthwhile to refactor the codebase to use manual DOM manipulation before Atom 1.16.0 is released.
