### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by k3rn31** [bh/atom-python-isort#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [python-isort](https://github.com/bh/atom-python-isort) package, v0.0.5

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/davide/.atom/packages/python-isort/lib/index.coffee:19

TypeError: undefined is not a function
  at atom-workspace.<anonymous> (/Users/davide/.atom/packages/python-isort/lib/index.coffee:19:10)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:336:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:35.9 command-palette:toggle (atom-text-editor.editor)
     -0:31.8 core:confirm (atom-text-editor.editor.mini)
     -0:31.8 python-isort:sortImports (atom-text-editor.editor)
     -0:21.9 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.3 core:confirm (atom-text-editor.editor.mini)
     -0:19.3 python-isort:sortImports (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.2 core:confirm (atom-text-editor.editor.mini)
     -0:08.1 python-isort:sortImports (atom-text-editor.editor.is-focused)
     -0:07.3 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:07.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.9 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.5 core:move-down (atom-text-editor.editor.mini)
     -0:03.0 core:confirm (atom-text-editor.editor.mini)
     -0:03.0 python-isort:checkImports (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-monokai"
    ],
    "projectHome": "/Users/davide/code"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.2
atom-django, v0.2.0
atom-monokai, v0.5.0
atom-python-debugger, v0.1.1
autocomplete-paths, v1.0.0
autocomplete-plus, v2.0.3
autocomplete-snippets, v1.0.0
emmet, v2.3.2
language-python-django-templates, v0.1.0
linter, v0.10.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-pep257, v0.1.4
linter-pep8, v0.1.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
minimap, v3.5.6
python-isort, v0.0.5
seti-ui, v0.6.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by lexicalunit** [comment]
@bh, can you release a new version of this package since merging in PR #12? This is still an issue using the latest version of `atom-python-sort`.

I believe this will also resolve issues #10, #11, #12, #13, #14, #15, and #17 :)

**Comment by bh** [comment]
Yeah tanks, I will make a release this week, I think. :+1:

**Comment by bh** [comment]
Done with 83c7582 :-)
